language: ruby
rvm:
- 2.2.0
script:
- bundle exec rspec spec
before_script:
- gem install travis-artifacts
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
addons:
  artifacts:
    debug: true
    bucket: ga-wdi-travis-logs/artifacts
    key:
      secure: RCdviNZ7hLeQU+iMgLp7fD0DIo1yBIp/ki/gkBehXKLzJcm+FmeaJu6FPJaQy20o4EBIhGWk3cTFI5LPufGe2sVCzBJHPEUuAR+DrIdAOwsYQtCkDB23FixjxnaqC66czZQtE1i4yq3qUBeVJjB+RyeTutOl6TZZUO3RaORHCzQ=
    secret:
      secure: EqtRwclZJ2oTRan3Ov8nNSk+Iz7YQzqmHYtVMJuml7IKzjkm22RPNQvNP8flR2VFeANEGBVeRO365+olbPZgBi+CzsIQ7UwguOMdfCNbEwfWXqnX1W0zQmeqWwX1jbefId5YPdzUWmJHz6B+3q7vcTfqPZegJSYMR7nWE/W/aOk=
deploy:
  provider: heroku
  app: gradingwizard
  api_key:
    secure: aJH/1UV5EtTtGbJzQzpa8oEz8a8EDFkr4yOYTSwjkA8sZscVueRufAalwBG/VOBlJF3hGCqwuUzqCVTS98LbuMvnA0GhhjGPK0wKoJpBkiNO1WX1WxXs1PjQa5JqRdbNweOyu2GjLmtOJ8P4yNjmGABObZeQOiGNxzztdULr3Q0=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
