language: ruby
rvm:
- 2.2.0
script:
- bundle exec rspec spec
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
deploy:
  provider: heroku
  app: gradingwizard
  api_key:
    secure: KyMslgxGjYYwx3AKs/ZuAV1aOfXSXNSLSDuAMrAwTjQd2JV7cz+DkxVrOpGb/Xkzggq59ZFAtsTyn7j3+1JPLUgCfToafcoEWvsSRkrao+wi/MurQgm2hXmeEW8S73B+Msca4NoF2ppy9L2YA2hypZaO4P3a19JAvPc6uMN2j5c=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
addons:
  artifacts:
    key:
      secure: Lk/Qf1Zp1J9QLU1WoR/dHH3AjOWQFYOoYfDvMEZ6bXVMBHkF/7M+UNVX6U/ECsfU53Dzu6LClRrGmbf9XTAmKZkAq+9Bo0Yri/B2IBwRk6ekNZiBsNLNSrZ2Oi3XtGfyO7OXJiaKkd686ReuMAzpHeVEla3N12T1kv733opZQj8=
    secret:
      secure: bbc6WeoXJ4U3u+jvOCfIV+BdGPXTVoseScGDKQfIoKgCLGDhoda9S5oqzf4U4maw/C5/LxdZbMqGpP7yWiw2Y67dZa3jzo7UfJbEStlaMl5e+Wg6RsM+ksymz9oPfhQE2BVsG1leziOPl3KbkddNni9GVYk5nty9v/LKxgniiOg=
    bucket: ga-wdi-travis-logs
