language: ruby
rvm:
- 2.2.0
script:
- bundle exec rspec spec
before_script:
- gem install travis-artifacts
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
deploy:
  provider: heroku
  app: gradingwizard
  api_key:
    secure: QQCQXZWK8cPY+CSMYXz0utXSp7TsFRuqbEyFur3D2IEauGoE5obIuaxh0MJNcsCo+sm3XebphrCaTlocjy68Kzw8ghEg8TGnPZv/Mb+yaF0j3avA1FqzWpMSnApOEdW24ZU7a5wsGPpTGuI9LmD4o++yeeZax2EfKxmyGpMyKrg=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
addons:
  artifacts:
    debug: true
    bucket: ga-wdi-travis-logs/artifacts
    key:
      secure: WINimOmRSO8fDOAW2PCzbK+3WkrNIJ2BDnEmvf6HvVoy4/cVhnDnjWP64LLW/MB0yjOnjVPuMHdsHcbRmtlBzoM0Ea9Klb2x7XcdnFX9C+SImbSVlcz6+kfktl0vmGjK3pXUFAaArfU+/o7weoFsocw4ZaxTJpUjqY0rbwdTwIk=
    secret:
      secure: GQuZ/1ZcN8cgWmFkADAiglQuGru+sji5jamPNkXEYZIuUN1mCBvHu1Opw2w8T96xZwbMIbTJoauCJlYGLw98MP2kCaE/NL+DpKVrm2kt2MiO3+tcFl3bvTAMxHYjHzho4OCQ2BZDWpecGqYeRVP36UkrthONR2l5bAG2Y+gkpoc=