language: ruby
rvm:
- 2.2.0
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=ga-wdi-travis-logs
  - secure: FPrIUS+n3uy6/S2ymifp4HgNrogQff3oq5ctnt1Mavd9XUMZFuiG5zXJ92ok0eb3KJBB7gFdAKLYEVSsHb54f3JqG4exAgtNuC/Wr72DgiHpnQnWpkaDJsuZzSOZ4BN4v3juI2JyWnjIfabig7Rf/E7haQOaJHSiATaAvxWX0nY=
  - secure: RTiMnOTBrqhZKilRf7GHViaIOsxB0eR/LegzhDXx/BjOd1u+lwnKnKXEQd2Mlw8wYTiUyuznlpKxaj6K/rgSKKjdYLifyQ4mx+tlfE8xQQBVRkBjL4LixmYuvGyMIFU1fs67+oltWGPtgTjVOy7jRVlfXmOBzYJqiE5BZpN57I4=
script:
- bundle exec rspec spec
before_script:
- gem install travis-artifacts
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
- after_test:
  - travis-artifacts upload --path logs --path artifacts/$TRAVIS_JOB_ID
deploy:
  provider: heroku
  app: gradingwizard
  api_key:
    secure: QQCQXZWK8cPY+CSMYXz0utXSp7TsFRuqbEyFur3D2IEauGoE5obIuaxh0MJNcsCo+sm3XebphrCaTlocjy68Kzw8ghEg8TGnPZv/Mb+yaF0j3avA1FqzWpMSnApOEdW24ZU7a5wsGPpTGuI9LmD4o++yeeZax2EfKxmyGpMyKrg=
  run:
  - rake db:migrate
  - rake db:seed
  - restart